[package]
name = "aoc-fetch"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
reqwest = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
regex = "1.10"